-- =============================================================================
-- CA Vida POC - Pipeline Orchestration Task DAG
-- =============================================================================
-- This DAG orchestrates the full ELT pipeline in the correct execution order:
--   Stage 1: Extraction (17 parallel COPY INTO)
--   Stage 2: Transformation (sequential, dependency-ordered)
--   Stage 3: Load to DW (SCD Type 2)
--
-- To execute manually (without tasks), run scripts in the order below.
-- To automate, resume the ROOT task.
-- =============================================================================

USE SCHEMA CAVIDA_POC.ORCHESTRATION;

-- ─────────────────────────────────────────────────────────────────────────────
-- ROOT TASK (trigger point)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK PIPELINE_ROOT
  WAREHOUSE = CAVIDA_POC_WH
  SCHEDULE = 'USING CRON 0 2 * * * Europe/Lisbon'  -- Daily at 02:00 Lisbon
  COMMENT = 'Root: triggers full ELT pipeline'
AS
  ALTER SESSION SET USE_CACHED_RESULT = FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- STAGE 1: EXTRACTION (all 17 run in parallel after ROOT)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK EXTRACT_ACTA00 WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_ACTA00_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/ACTA00/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_ACTA03 WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_ACTA03_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/ACTA03/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_ACTA0P WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_ACTA0P_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/ACTA0P/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_APOL00 WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_APOL00_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/APOL00/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_APOL03 WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_APOL03_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/APOL03/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_APOL0PH WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_APOL0PH_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/APOL0PH/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_APOL0P WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_APOL0P_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/APOL0P/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_APOLPA WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_APOLPA_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/APOLPA/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_ENTREL WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_ENTREL_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/ENTREL/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_ENTVIN WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_ENTVIN_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/ENTVIN/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_EVENTO WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_EVENTO_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/EVENTO/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_MOPEC1 WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_MOPEC1_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/MOPEC1/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_MOVIML WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_MOVIML_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/MOVIML/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_RECI0X WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_RECI0X_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/RECI0X/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_RECIBO WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_RECIBO_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/RECIBO/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1_RECIBO ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_RECPRO WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_RECPRO_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/RECPRO/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK EXTRACT_RECREL WAREHOUSE = CAVIDA_POC_WH AFTER PIPELINE_ROOT AS
  COPY INTO CAVIDA_POC.EXTRACTION.DB2_RECREL_POC FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/RECREL/ FILE_FORMAT = CAVIDA_POC.EXTRACTION.CSV_LATIN1 ON_ERROR = 'CONTINUE';

-- ─────────────────────────────────────────────────────────────────────────────
-- BARRIER: All extractions must complete before transformations start
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK BARRIER_EXTRACTION_COMPLETE
  WAREHOUSE = CAVIDA_POC_WH
  AFTER EXTRACT_ACTA00, EXTRACT_ACTA03, EXTRACT_ACTA0P, EXTRACT_APOL00,
       EXTRACT_APOL03, EXTRACT_APOL0PH, EXTRACT_APOL0P, EXTRACT_APOLPA,
       EXTRACT_ENTREL, EXTRACT_ENTVIN, EXTRACT_EVENTO, EXTRACT_MOPEC1,
       EXTRACT_MOVIML, EXTRACT_RECI0X, EXTRACT_RECIBO, EXTRACT_RECPRO,
       EXTRACT_RECREL
AS
  SELECT 'Extraction complete: all 17 tables loaded' AS STATUS;

-- ─────────────────────────────────────────────────────────────────────────────
-- STAGE 2: TRANSFORMATIONS (sequential, respecting dependencies)
-- ─────────────────────────────────────────────────────────────────────────────

-- UOE Path (sequential: 003 → 005)
CREATE OR REPLACE TASK TRANSFORM_UOE_003
  WAREHOUSE = CAVIDA_POC_WH
  AFTER BARRIER_EXTRACTION_COMPLETE
  COMMENT = 'UOE Step 3: FULL JOIN + RIGHT JOIN chain'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/INSPOL_LIFEUNITOFEXPOSURE_003.sql;

CREATE OR REPLACE TASK TRANSFORM_UOE_005
  WAREHOUSE = CAVIDA_POC_WH
  AFTER TRANSFORM_UOE_003
  COMMENT = 'UOE Step 5: LAG/LEAD window functions, parity logic'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/INSPOL_LIFEUNITOFEXPOSURE_005.sql;

-- LPT Path (sequential: 001 → 002 → 003)
CREATE OR REPLACE TASK TRANSFORM_LPT_001
  WAREHOUSE = CAVIDA_POC_WH
  AFTER BARRIER_EXTRACTION_COMPLETE
  COMMENT = 'LPT Step 1: Row explosion (1→6 UNION ALL) + 4-table join'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/INSPOL_LIFEPOLICYTRANS_001.sql;

CREATE OR REPLACE TASK TRANSFORM_LPT_002
  WAREHOUSE = CAVIDA_POC_WH
  AFTER TRANSFORM_LPT_001
  COMMENT = 'LPT Step 2: Employee lookup + X_PROCESSED_FLG state machine'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/INSPOL_LIFEPOLICYTRANS_002.sql;

CREATE OR REPLACE TASK TRANSFORM_LPT_003
  WAREHOUSE = CAVIDA_POC_WH
  AFTER TRANSFORM_LPT_002
  COMMENT = 'LPT Step 3: Append status-2 rows + RECREL + filter'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/INSPOL_LIFEPOLICYTRANS_003.sql;

-- ─────────────────────────────────────────────────────────────────────────────
-- BARRIER: All transformations must complete before DW load
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK BARRIER_TRANSFORM_COMPLETE
  WAREHOUSE = CAVIDA_POC_WH
  AFTER TRANSFORM_UOE_005, TRANSFORM_LPT_003
AS
  SELECT 'Transformation complete: staging tables ready for DW load' AS STATUS;

-- ─────────────────────────────────────────────────────────────────────────────
-- STAGE 3: DW LOAD (SCD Type 2 - can run in parallel)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK LOAD_UOE
  WAREHOUSE = CAVIDA_POC_WH
  AFTER BARRIER_TRANSFORM_COMPLETE
  COMMENT = 'SCD2 load: LIFE_UNIT_OF_EXPOSURE (24.2M rows)'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/LOAD_LIFEUNITOFEXPOSURE.sql;

CREATE OR REPLACE TASK LOAD_LPT
  WAREHOUSE = CAVIDA_POC_WH
  AFTER BARRIER_TRANSFORM_COMPLETE
  COMMENT = 'Splitter load: LIFE_POLICY_TRANS + X_LIFE_POLICY_TRANS_HIST'
AS
  EXECUTE IMMEDIATE FROM @CAVIDA_POC.EXTRACTION.INPUT_DATA/scripts/LOAD_LIFEPOLICYTRANS.sql;

-- ─────────────────────────────────────────────────────────────────────────────
-- FINAL: Pipeline complete marker
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE TASK PIPELINE_COMPLETE
  WAREHOUSE = CAVIDA_POC_WH
  AFTER LOAD_UOE, LOAD_LPT
AS
  INSERT INTO CAVIDA_POC.ORCHESTRATION.PIPELINE_MONITOR_LOG 
    (CHECK_TYPE, STATUS, DETAILS)
  VALUES (
    'PIPELINE_RUN',
    'COMPLETE',
    OBJECT_CONSTRUCT(
      'completed_at', CURRENT_TIMESTAMP()::VARCHAR,
      'uoe_rows', (SELECT COUNT(*) FROM CAVIDA_POC.DW.LIFE_UNIT_OF_EXPOSURE),
      'lpt_rows', (SELECT COUNT(*) FROM CAVIDA_POC.DW.LIFE_POLICY_TRANS)
    )
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- RESUME ALL TASKS (bottom-up order required)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TASK PIPELINE_COMPLETE RESUME;
ALTER TASK LOAD_UOE RESUME;
ALTER TASK LOAD_LPT RESUME;
ALTER TASK BARRIER_TRANSFORM_COMPLETE RESUME;
ALTER TASK TRANSFORM_UOE_005 RESUME;
ALTER TASK TRANSFORM_LPT_003 RESUME;
ALTER TASK TRANSFORM_LPT_002 RESUME;
ALTER TASK TRANSFORM_LPT_001 RESUME;
ALTER TASK TRANSFORM_UOE_003 RESUME;
ALTER TASK BARRIER_EXTRACTION_COMPLETE RESUME;
ALTER TASK EXTRACT_ACTA00 RESUME;
ALTER TASK EXTRACT_ACTA03 RESUME;
ALTER TASK EXTRACT_ACTA0P RESUME;
ALTER TASK EXTRACT_APOL00 RESUME;
ALTER TASK EXTRACT_APOL03 RESUME;
ALTER TASK EXTRACT_APOL0PH RESUME;
ALTER TASK EXTRACT_APOL0P RESUME;
ALTER TASK EXTRACT_APOLPA RESUME;
ALTER TASK EXTRACT_ENTREL RESUME;
ALTER TASK EXTRACT_ENTVIN RESUME;
ALTER TASK EXTRACT_EVENTO RESUME;
ALTER TASK EXTRACT_MOPEC1 RESUME;
ALTER TASK EXTRACT_MOVIML RESUME;
ALTER TASK EXTRACT_RECI0X RESUME;
ALTER TASK EXTRACT_RECIBO RESUME;
ALTER TASK EXTRACT_RECPRO RESUME;
ALTER TASK EXTRACT_RECREL RESUME;
ALTER TASK PIPELINE_ROOT RESUME;

-- ─────────────────────────────────────────────────────────────────────────────
-- MANUAL EXECUTION (trigger immediately without waiting for schedule)
-- ─────────────────────────────────────────────────────────────────────────────
-- EXECUTE TASK PIPELINE_ROOT;
