CREATE OR REPLACE TRANSIENT TABLE CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_005 AS
WITH
step1_base_cov_indv AS (
    SELECT
        LPAD("A0$MOD"::VARCHAR, 2, '0') || LPAD("A0$APL"::VARCHAR, 8, '0') AS POLICY_NO,
        LPAD("A0$MOD"::VARCHAR, 2, '0') || LPAD(A0NAPO::VARCHAR, 8, '0') AS PROPOSAL_NO,
        A0ACTA AS POLICY_VERSION,
        '0' AS X_COVERAGE_CD,
        '0' AS X_ORDER_CD,
        A0PRSC / 100.0 AS ANNUAL_PREMIUM_AMT,
        A0CTOT / 100.0 AS CASH_VALUE,
        A0INDX AS X_INDEXATION_RT,
        TRY_TO_DATE(LPAD(A0AINI::VARCHAR,4,'0') || LPAD(A0MINI::VARCHAR,2,'0') || LPAD(A0DINI::VARCHAR,2,'0'), 'YYYYMMDD') AS ADMISSION_DT,
        TRY_TO_DATE(LPAD(A0AINI::VARCHAR,4,'0') || LPAD(A0MINI::VARCHAR,2,'0') || LPAD(A0DINI::VARCHAR,2,'0'), 'YYYYMMDD') AS EFFECTIVE_DT,
        TRY_TO_DATE(LPAD(A0AFIM::VARCHAR,4,'0') || LPAD(A0MFIM::VARCHAR,2,'0') || LPAD(A0DFIM::VARCHAR,2,'0'), 'YYYYMMDD') AS EXPIRATION_DT,
        TRY_TO_DATE(LPAD(A0AFIM::VARCHAR,4,'0') || LPAD(A0MFIM::VARCHAR,2,'0') || LPAD(A0DFIM::VARCHAR,2,'0'), 'YYYYMMDD') AS TERMINATION_DT,
        A0DURC AS RENEWABLE_IND,
        TRY_TO_DATE(LPAD(A0AINI::VARCHAR,4,'0') || LPAD(A0MINI::VARCHAR,2,'0') || LPAD(A0DINI::VARCHAR,2,'0'), 'YYYYMMDD')::TIMESTAMP_NTZ AS CHANGE_EFFECTIVE_FROM_DTTM,
        '5999-01-01'::TIMESTAMP_NTZ AS CHANGE_EFFECTIVE_TO_DTTM,
        CASE
            WHEN TRIM(A0SITU::VARCHAR) = '.' OR A0SITU IS NULL THEN ''
            ELSE TRIM(A0SITU::VARCHAR)
        END AS POLICY_STATUS_CD
    FROM CAVIDA_POC.EXTRACTION.DB2_APOL00_POC
    WHERE "A0$MOD" != 8
      AND "A0$APL" != 0
      AND A0INF4 != 'S'
      AND A0ACTA = 0
),

step2_anti_join_base_vs_uoe004 AS (
    SELECT
        s1.POLICY_NO,
        s1.PROPOSAL_NO,
        s1.POLICY_VERSION,
        s1.X_COVERAGE_CD,
        s1.X_ORDER_CD,
        s1.ANNUAL_PREMIUM_AMT,
        s1.CASH_VALUE,
        s1.X_INDEXATION_RT,
        s1.ADMISSION_DT,
        s1.EFFECTIVE_DT,
        s1.EXPIRATION_DT,
        s1.TERMINATION_DT,
        s1.RENEWABLE_IND,
        s1.CHANGE_EFFECTIVE_FROM_DTTM,
        s1.CHANGE_EFFECTIVE_TO_DTTM,
        s1.POLICY_STATUS_CD
    FROM step1_base_cov_indv s1
    WHERE NOT EXISTS (
        SELECT 1
        FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_004 u4
        WHERE s1.PROPOSAL_NO = u4.PROPOSAL_NO
          AND s1.POLICY_VERSION = u4.POLICY_VERSION
          AND s1.X_COVERAGE_CD = u4.X_COVERAGE_CD
          AND s1.X_ORDER_CD = u4.X_ORDER_CD
          AND s1.POLICY_NO = u4.POLICY_NO
    )
),

step3_anti_join_uoe003_vs_uoe004 AS (
    SELECT
        u3.POLICY_NO,
        u3.PROPOSAL_NO,
        u3.POLICY_VERSION,
        u3.X_COVERAGE_CD,
        u3.X_ORDER_CD,
        u3.ANNUAL_PREMIUM_AMT,
        u3.CASH_VALUE,
        u3.X_INDEXATION_RT,
        u3.ADMISSION_DT,
        u3.EFFECTIVE_DT,
        u3.EXPIRATION_DT,
        u3.TERMINATION_DT,
        u3.RENEWABLE_IND,
        u3.CHANGE_EFFECTIVE_FROM_DTTM,
        u3.CHANGE_EFFECTIVE_TO_DTTM,
        u3.POLICY_STATUS_CD
    FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_003 u3
    WHERE NOT EXISTS (
        SELECT 1
        FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_004 u4
        WHERE u3.PROPOSAL_NO = u4.PROPOSAL_NO
          AND u3.POLICY_VERSION = u4.POLICY_VERSION
          AND u3.X_COVERAGE_CD = u4.X_COVERAGE_CD
          AND u3.X_ORDER_CD = u4.X_ORDER_CD
          AND u3.POLICY_NO = u4.POLICY_NO
    )
),

step4_append_all AS (
    SELECT POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
           POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
           ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
           RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM
    FROM step2_anti_join_base_vs_uoe004
    UNION ALL
    SELECT POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
           POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
           ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
           RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM
    FROM step3_anti_join_uoe003_vs_uoe004
    UNION ALL
    SELECT POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
           POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
           NULL AS ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
           RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, NULL AS CHANGE_EFFECTIVE_TO_DTTM
    FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_004
),

step5_coalesce_admission AS (
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
        COALESCE(ADMISSION_DT, EFFECTIVE_DT) AS ADMISSION_DT,
        EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT, RENEWABLE_IND,
        CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM
    FROM step4_append_all
),

step7_user_written_pass1 AS (
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        ADMISSION_DT,
        CHANGE_EFFECTIVE_FROM_DTTM AS ORIG_CHANGE_EFFECTIVE_FROM_DTTM,
        ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) AS rn_desc,
        ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION ASC) AS rn_asc,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN NULL
            ELSE LAG(ANNUAL_PREMIUM_AMT) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS ANNUAL_PREMIUM_AMT,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN NULL
            ELSE LAG(CASH_VALUE) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS CASH_VALUE,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN ''
            ELSE LAG(POLICY_STATUS_CD) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS POLICY_STATUS_CD,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN NULL
            ELSE LAG(TERMINATION_DT) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS TERMINATION_DT,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN NULL
            ELSE LAG(X_INDEXATION_RT) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS X_INDEXATION_RT,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                 AND SUBSTR(POLICY_NO, 1, 2) != '08'
                THEN NULL
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                 AND SUBSTR(POLICY_NO, 1, 2) = '08'
                THEN EFFECTIVE_DT
            WHEN SUBSTR(POLICY_NO, 1, 2) != '08'
                THEN LAG(EFFECTIVE_DT) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
            ELSE EFFECTIVE_DT
        END AS EFFECTIVE_DT,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN NULL
            ELSE LAG(EXPIRATION_DT) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS EXPIRATION_DT,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC) = 1
                THEN ''
            ELSE LAG(RENEWABLE_IND) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION DESC)
        END AS RENEWABLE_IND,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD ORDER BY POLICY_VERSION ASC) = 1
                THEN NULL
            ELSE CHANGE_EFFECTIVE_FROM_DTTM
        END AS CHANGE_EFFECTIVE_FROM_DTTM
    FROM step5_coalesce_admission
),

step7_user_written AS (
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        ADMISSION_DT, ANNUAL_PREMIUM_AMT, CASH_VALUE, POLICY_STATUS_CD,
        TERMINATION_DT, X_INDEXATION_RT, EFFECTIVE_DT, EXPIRATION_DT,
        RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM,
        CASE
            WHEN ROW_NUMBER() OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD
                                    ORDER BY POLICY_VERSION DESC, CHANGE_EFFECTIVE_FROM_DTTM DESC NULLS LAST) = 1
                THEN '5999-01-01'::TIMESTAMP_NTZ
            ELSE LAG(CHANGE_EFFECTIVE_FROM_DTTM) OVER (PARTITION BY POLICY_NO, X_ORDER_CD, X_COVERAGE_CD
                                                        ORDER BY POLICY_VERSION DESC, CHANGE_EFFECTIVE_FROM_DTTM DESC NULLS LAST)
        END AS CHANGE_EFFECTIVE_TO_DTTM
    FROM step7_user_written_pass1
),

step8_fill_complement_cov AS (
    SELECT
        w.POLICY_NO,
        w.PROPOSAL_NO,
        w.POLICY_VERSION,
        w.X_COVERAGE_CD,
        w.X_ORDER_CD,
        COALESCE(NULLIF(w.POLICY_STATUS_CD, ''), TRIM(REPLACE(a3.A3SITU::VARCHAR, '.', ''))) AS POLICY_STATUS_CD,
        COALESCE(w.ANNUAL_PREMIUM_AMT, a3.A3PREM / 100.0) AS ANNUAL_PREMIUM_AMT,
        COALESCE(w.CASH_VALUE, a3.A3CAPT / 100.0) AS CASH_VALUE,
        COALESCE(w.X_INDEXATION_RT, a3.A3INDX) AS X_INDEXATION_RT,
        w.ADMISSION_DT,
        COALESCE(w.EFFECTIVE_DT, TRY_TO_DATE(LPAD(a3.A3AINI::VARCHAR,4,'0') || LPAD(a3.A3MINI::VARCHAR,2,'0') || LPAD(a3.A3DINI::VARCHAR,2,'0'), 'YYYYMMDD')) AS EFFECTIVE_DT,
        COALESCE(w.EXPIRATION_DT, TRY_TO_DATE(LPAD(a3.A3AFIM::VARCHAR,4,'0') || LPAD(a3.A3MFIM::VARCHAR,2,'0') || LPAD(a3.A3DFIM::VARCHAR,2,'0'), 'YYYYMMDD')) AS EXPIRATION_DT,
        w.TERMINATION_DT,
        COALESCE(w.RENEWABLE_IND, a3.A3DURC) AS RENEWABLE_IND,
        w.CHANGE_EFFECTIVE_FROM_DTTM,
        w.CHANGE_EFFECTIVE_TO_DTTM
    FROM step7_user_written w
    LEFT JOIN CAVIDA_POC.EXTRACTION.DB2_APOL03_POC a3
        ON w.PROPOSAL_NO = LPAD(a3."A3$MOD"::VARCHAR, 2, '0') || LPAD(a3.A3NAPO::VARCHAR, 8, '0')
        AND TRIM(a3.A3NORD::VARCHAR) = TRIM(w.X_ORDER_CD)
        AND TRIM(a3."A3$CMP"::VARCHAR) = TRIM(w.X_COVERAGE_CD)
        AND w.X_COVERAGE_CD != '0'
    WHERE NOT (
        w.X_COVERAGE_CD != '0'
        AND COALESCE(w.CASH_VALUE, a3.A3CAPT / 100.0) IS NULL
        AND COALESCE(w.ANNUAL_PREMIUM_AMT, a3.A3PREM / 100.0) IS NULL
        AND w.CHANGE_EFFECTIVE_TO_DTTM::DATE = '5999-01-01'::DATE
    )
),

step9_fill_base_cov AS (
    SELECT
        w.POLICY_NO,
        w.PROPOSAL_NO,
        w.POLICY_VERSION,
        w.X_COVERAGE_CD,
        w.X_ORDER_CD,
        CASE
            WHEN TRIM(w.POLICY_STATUS_CD) = '' OR w.POLICY_STATUS_CD IS NULL
                THEN TRIM(REPLACE(a0.A0SITU::VARCHAR, '.', ''))
            ELSE w.POLICY_STATUS_CD
        END AS POLICY_STATUS_CD,
        COALESCE(w.ANNUAL_PREMIUM_AMT, a0.A0PRSC / 100.0) AS ANNUAL_PREMIUM_AMT,
        COALESCE(w.CASH_VALUE, a0.A0CTOT / 100.0) AS CASH_VALUE,
        w.X_INDEXATION_RT,
        w.ADMISSION_DT,
        COALESCE(w.EFFECTIVE_DT, TRY_TO_DATE(LPAD(a0.A0AINI::VARCHAR,4,'0') || LPAD(a0.A0MINI::VARCHAR,2,'0') || LPAD(a0.A0DINI::VARCHAR,2,'0'), 'YYYYMMDD')) AS EFFECTIVE_DT,
        COALESCE(w.EXPIRATION_DT, TRY_TO_DATE(LPAD(a0.A0AFIM::VARCHAR,4,'0') || LPAD(a0.A0MFIM::VARCHAR,2,'0') || LPAD(a0.A0DFIM::VARCHAR,2,'0'), 'YYYYMMDD')) AS EXPIRATION_DT,
        w.TERMINATION_DT,
        w.RENEWABLE_IND,
        w.CHANGE_EFFECTIVE_FROM_DTTM,
        w.CHANGE_EFFECTIVE_TO_DTTM
    FROM step8_fill_complement_cov w
    LEFT JOIN CAVIDA_POC.EXTRACTION.DB2_APOL00_POC a0
        ON w.POLICY_NO = LPAD(a0."A0$MOD"::VARCHAR, 2, '0') || LPAD(a0."A0$APL"::VARCHAR, 8, '0')
        AND a0."A0$MOD" != 8
        AND w.X_COVERAGE_CD = '0'
        AND a0."A0$APL" != 0
),

step10_fill_change_from AS (
    SELECT DISTINCT
        w.POLICY_NO,
        w.PROPOSAL_NO,
        w.POLICY_VERSION,
        w.X_COVERAGE_CD,
        w.X_ORDER_CD,
        CASE
            WHEN SUBSTR(w.POLICY_NO, 1, 2) = '08' AND w.X_COVERAGE_CD = '0'
                THEN COALESCE(w.POLICY_STATUS_CD, TRIM(a0.A0SITU::VARCHAR))
            ELSE w.POLICY_STATUS_CD
        END AS POLICY_STATUS_CD,
        w.ANNUAL_PREMIUM_AMT,
        w.CASH_VALUE,
        w.X_INDEXATION_RT,
        w.ADMISSION_DT,
        CASE
            WHEN SUBSTR(w.POLICY_NO, 1, 2) = '08' AND w.X_COVERAGE_CD = '0'
                THEN COALESCE(w.EFFECTIVE_DT, TRY_TO_DATE(LPAD(a0.A0AINI::VARCHAR,4,'0') || LPAD(a0.A0MINI::VARCHAR,2,'0') || LPAD(a0.A0DINI::VARCHAR,2,'0'), 'YYYYMMDD'))
            ELSE w.EFFECTIVE_DT
        END AS EFFECTIVE_DT,
        CASE
            WHEN SUBSTR(w.POLICY_NO, 1, 2) = '08' AND w.X_COVERAGE_CD = '0'
                THEN COALESCE(w.EXPIRATION_DT, TRY_TO_DATE(LPAD(a0.A0AFIM::VARCHAR,4,'0') || LPAD(a0.A0MFIM::VARCHAR,2,'0') || LPAD(a0.A0DFIM::VARCHAR,2,'0'), 'YYYYMMDD'))
            ELSE w.EXPIRATION_DT
        END AS EXPIRATION_DT,
        CASE
            WHEN w.TERMINATION_DT IS NULL AND a0.A0SITU = 3
                THEN TRY_TO_DATE(LPAD(a0.A0ASIT::VARCHAR,4,'0') || LPAD(a0.A0MSIT::VARCHAR,2,'0') || LPAD(a0.A0DSIT::VARCHAR,2,'0'), 'YYYYMMDD')
            WHEN w.TERMINATION_DT IS NULL AND a0.A0SITU != 3
                THEN TRY_TO_DATE(LPAD(a0.A0AFIM::VARCHAR,4,'0') || LPAD(a0.A0MFIM::VARCHAR,2,'0') || LPAD(a0.A0DFIM::VARCHAR,2,'0'), 'YYYYMMDD')
            ELSE w.TERMINATION_DT
        END AS TERMINATION_DT,
        w.RENEWABLE_IND,
        CASE
            WHEN w.CHANGE_EFFECTIVE_FROM_DTTM IS NULL
                 AND (SUBSTR(w.POLICY_NO, 1, 2) != '08'
                      OR (SUBSTR(w.POLICY_NO, 1, 2) = '08' AND w.POLICY_VERSION = 0))
                THEN LEAST(
                    TRY_TO_DATE(LPAD(a0.A0APMB::VARCHAR,4,'0') || LPAD(a0.A0MPMB::VARCHAR,2,'0') || LPAD(a0.A0DPMB::VARCHAR,2,'0'), 'YYYYMMDD')::TIMESTAMP_NTZ,
                    TRY_TO_DATE(LPAD(a0.A0AINI::VARCHAR,4,'0') || LPAD(a0.A0MINI::VARCHAR,2,'0') || LPAD(a0.A0DINI::VARCHAR,2,'0'), 'YYYYMMDD')::TIMESTAMP_NTZ
                )
            WHEN w.CHANGE_EFFECTIVE_FROM_DTTM IS NULL
                 AND SUBSTR(w.POLICY_NO, 1, 2) = '08'
                 AND a0.A0ACTA = w.POLICY_VERSION
                THEN TRY_TO_DATE(LPAD(a0.A0AEFE::VARCHAR,4,'0') || LPAD(a0.A0MEFE::VARCHAR,2,'0') || LPAD(a0.A0DEFE::VARCHAR,2,'0'), 'YYYYMMDD')::TIMESTAMP_NTZ
            ELSE w.CHANGE_EFFECTIVE_FROM_DTTM
        END AS CHANGE_EFFECTIVE_FROM_DTTM,
        w.CHANGE_EFFECTIVE_TO_DTTM
    FROM step9_fill_base_cov w
    LEFT JOIN CAVIDA_POC.EXTRACTION.DB2_APOL00_POC a0
        ON w.POLICY_NO = LPAD(a0."A0$MOD"::VARCHAR, 2, '0') || LPAD(a0."A0$APL"::VARCHAR, 8, '0')
),

step11_last_image AS (
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
        ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
        RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM
    FROM step10_fill_change_from
    WHERE CHANGE_EFFECTIVE_TO_DTTM::DATE = '5999-01-01'::DATE
),

step12_last_policy_status AS (
    SELECT
        w.POLICY_NO,
        w.PROPOSAL_NO,
        w.POLICY_VERSION,
        w.X_COVERAGE_CD,
        w.X_ORDER_CD,
        CASE WHEN a0.A0SITU = 3 THEN '3' ELSE w.POLICY_STATUS_CD END AS POLICY_STATUS_CD,
        w.ANNUAL_PREMIUM_AMT,
        w.CASH_VALUE,
        w.X_INDEXATION_RT,
        w.ADMISSION_DT,
        w.EFFECTIVE_DT,
        w.EXPIRATION_DT,
        w.TERMINATION_DT,
        w.RENEWABLE_IND,
        w.CHANGE_EFFECTIVE_FROM_DTTM,
        CASE
            WHEN a0.A0SITU = 3
                THEN TRY_TO_DATE(LPAD(a0.A0ASIT::VARCHAR,4,'0') || LPAD(a0.A0MSIT::VARCHAR,2,'0') || LPAD(a0.A0DSIT::VARCHAR,2,'0'), 'YYYYMMDD')::TIMESTAMP_NTZ
            ELSE w.CHANGE_EFFECTIVE_TO_DTTM
        END AS CHANGE_EFFECTIVE_TO_DTTM,
        a0.A0SITU
    FROM step11_last_image w
    LEFT JOIN CAVIDA_POC.EXTRACTION.DB2_APOL00_POC a0
        ON w.POLICY_NO = LPAD(a0."A0$MOD"::VARCHAR, 2, '0') || LPAD(a0."A0$APL"::VARCHAR, 8, '0')
),

step13_change_last_image_anuladas AS (
    SELECT
        base.POLICY_NO,
        base.PROPOSAL_NO,
        base.POLICY_VERSION,
        base.X_COVERAGE_CD,
        base.X_ORDER_CD,
        COALESCE(lst.POLICY_STATUS_CD, base.POLICY_STATUS_CD) AS POLICY_STATUS_CD,
        base.ANNUAL_PREMIUM_AMT,
        base.CASH_VALUE,
        base.X_INDEXATION_RT,
        base.ADMISSION_DT,
        base.EFFECTIVE_DT,
        base.EXPIRATION_DT,
        base.TERMINATION_DT,
        base.RENEWABLE_IND,
        base.CHANGE_EFFECTIVE_FROM_DTTM,
        CASE
            WHEN lst.A0SITU = 3 THEN lst.CHANGE_EFFECTIVE_TO_DTTM
            ELSE base.CHANGE_EFFECTIVE_TO_DTTM
        END AS CHANGE_EFFECTIVE_TO_DTTM,
        COALESCE(lst.POLICY_STATUS_CD, base.POLICY_STATUS_CD) AS X_ORDER_STATUS,
        CASE
            WHEN lst.POLICY_STATUS_CD = '3' THEN lst.CHANGE_EFFECTIVE_TO_DTTM::DATE
            ELSE base.ADMISSION_DT
        END AS X_ORDER_STATUS_DT
    FROM step10_fill_change_from base
    LEFT JOIN step12_last_policy_status lst
        ON base.POLICY_NO = lst.POLICY_NO
        AND base.POLICY_VERSION = lst.POLICY_VERSION
        AND base.X_COVERAGE_CD = lst.X_COVERAGE_CD
        AND base.X_ORDER_CD = lst.X_ORDER_CD
),

step14_extract_uoe002 AS (
    SELECT
        POLICY_NO,
        PROPOSAL_NO,
        POLICY_VERSION - 1 AS POLICY_VERSION,
        POLICY_STATUS_CD,
        X_ORDER_CD,
        ADMISSION_DT,
        X_ORDER_STATUS,
        X_ORDER_STATUS_DT,
        X_COVERAGE_CD,
        ANNUAL_PREMIUM_AMT,
        CASH_VALUE,
        EXPIRATION_DT,
        TERMINATION_DT,
        X_INDEXATION_RT,
        EFFECTIVE_DT,
        RENEWABLE_IND
    FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_002
),

step15_join_insurance_policy AS (
    SELECT
        w.POLICY_NO,
        w.PROPOSAL_NO,
        w.POLICY_VERSION,
        TRIM(w.POLICY_STATUS_CD) AS POLICY_STATUS_CD,
        w.X_ORDER_CD,
        w.ADMISSION_DT,
        w.X_ORDER_STATUS,
        w.X_ORDER_STATUS_DT,
        w.X_COVERAGE_CD,
        w.ANNUAL_PREMIUM_AMT,
        w.CASH_VALUE,
        w.EXPIRATION_DT,
        w.TERMINATION_DT,
        w.X_INDEXATION_RT,
        w.EFFECTIVE_DT,
        w.RENEWABLE_IND,
        ip.CHANGE_EFFECTIVE_FROM_DTTM,
        ip.CHANGE_EFFECTIVE_TO_DTTM
    FROM step14_extract_uoe002 w
    LEFT JOIN CAVIDA_POC.POC_LOOK.INSPOL_INSURANCEPOLICY ip
        ON w.POLICY_NO = ip.POLICY_NO
        AND w.POLICY_VERSION = ip.POLICY_VERSION
),

step16_final_append AS (
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
        ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
        RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM,
        X_ORDER_STATUS, X_ORDER_STATUS_DT
    FROM step13_change_last_image_anuladas
    UNION ALL
    SELECT
        POLICY_NO, PROPOSAL_NO, POLICY_VERSION, X_COVERAGE_CD, X_ORDER_CD,
        POLICY_STATUS_CD, ANNUAL_PREMIUM_AMT, CASH_VALUE, X_INDEXATION_RT,
        ADMISSION_DT, EFFECTIVE_DT, EXPIRATION_DT, TERMINATION_DT,
        RENEWABLE_IND, CHANGE_EFFECTIVE_FROM_DTTM, CHANGE_EFFECTIVE_TO_DTTM,
        X_ORDER_STATUS, X_ORDER_STATUS_DT
    FROM step15_join_insurance_policy
)

SELECT
    POLICY_NO,
    PROPOSAL_NO,
    POLICY_VERSION,
    X_COVERAGE_CD,
    X_ORDER_CD,
    POLICY_STATUS_CD,
    ANNUAL_PREMIUM_AMT,
    CASH_VALUE,
    X_INDEXATION_RT,
    ADMISSION_DT,
    EFFECTIVE_DT,
    EXPIRATION_DT,
    TERMINATION_DT,
    RENEWABLE_IND,
    CHANGE_EFFECTIVE_FROM_DTTM,
    CHANGE_EFFECTIVE_TO_DTTM,
    X_ORDER_STATUS,
    X_ORDER_STATUS_DT
FROM step16_final_append;
