CREATE OR REPLACE TABLE CAVIDA_POC.DW.LIFE_UNIT_OF_EXPOSURE AS
WITH lookup_insurance_policy AS (
    SELECT POLICY_NO, POLICY_RK
    FROM (
        SELECT POLICY_NO, POLICY_RK,
               ROW_NUMBER() OVER (PARTITION BY POLICY_NO ORDER BY VALID_TO_DTTM DESC) AS rn
        FROM CAVIDA_POC.DW.INSURANCE_POLICY
    )
    WHERE rn = 1
),
lookup_proposal AS (
    SELECT PROPOSAL_NO, X_POLICY_PROPOSAL_RK
    FROM (
        SELECT PROPOSAL_NO, X_POLICY_PROPOSAL_RK,
               ROW_NUMBER() OVER (PARTITION BY PROPOSAL_NO ORDER BY VALID_TO_DTTM DESC) AS rn
        FROM CAVIDA_POC.DW.X_INSURANCE_PROPOSAL
    )
    WHERE rn = 1
),
lookup_coverage AS (
    SELECT COVERAGE_CD, COVERAGE_RK
    FROM (
        SELECT COVERAGE_CD, COVERAGE_RK,
               ROW_NUMBER() OVER (PARTITION BY COVERAGE_CD ORDER BY VALID_TO_DTTM DESC) AS rn
        FROM CAVIDA_POC.DW.COVERAGE
    )
    WHERE rn = 1
),
lookup_product_category AS (
    SELECT PRODUCT_CATEGORY_CD, PRODUCT_CATEGORY_RK
    FROM (
        SELECT PRODUCT_CATEGORY_CD, PRODUCT_CATEGORY_RK,
               ROW_NUMBER() OVER (PARTITION BY PRODUCT_CATEGORY_CD ORDER BY VALID_TO_DTTM DESC) AS rn
        FROM CAVIDA_POC.DW.PRODUCT_CATEGORY
    )
    WHERE rn = 1
),
extracted AS (
    SELECT
        src.POLICY_NO,
        src.PROPOSAL_NO,
        src.POLICY_VERSION AS X_POLICY_VERSION,
        src.X_COVERAGE_CD,
        src.X_ORDER_CD,
        src.POLICY_STATUS_CD AS X_POLICY_STATUS_CD,
        src.ANNUAL_PREMIUM_AMT,
        src.CASH_VALUE,
        src.X_INDEXATION_RT,
        src.ADMISSION_DT AS X_ADMISSION_DT,
        src.EFFECTIVE_DT,
        src.EXPIRATION_DT,
        src.TERMINATION_DT AS X_POLICY_TERMINATION_DT,
        src.RENEWABLE_IND,
        src.X_ORDER_STATUS,
        src.X_ORDER_STATUS_DT,
        src.CHANGE_EFFECTIVE_FROM_DTTM,
        src.CHANGE_EFFECTIVE_TO_DTTM,
        TRIM(SUBSTR(src.POLICY_NO, 1, 2)) AS PRODUCT_CATEGORY_CD,
        CURRENT_TIMESTAMP() AS PROCESSED_DTTM
    FROM CAVIDA_POC.STAGING.INSPOL_LIFEUNITOFEXPOSURE_005 src
),
with_lookups AS (
    SELECT
        lip.POLICY_RK,
        lp.X_POLICY_PROPOSAL_RK,
        e.X_POLICY_VERSION,
        e.X_ORDER_CD,
        lc.COVERAGE_RK AS COVERAGE_RIDER_RK,
        e.X_POLICY_STATUS_CD,
        e.ANNUAL_PREMIUM_AMT,
        e.CASH_VALUE,
        e.X_INDEXATION_RT,
        e.X_ADMISSION_DT,
        e.EFFECTIVE_DT,
        e.EXPIRATION_DT,
        e.X_POLICY_TERMINATION_DT,
        e.RENEWABLE_IND,
        e.X_ORDER_STATUS,
        e.X_ORDER_STATUS_DT,
        e.CHANGE_EFFECTIVE_FROM_DTTM,
        e.CHANGE_EFFECTIVE_TO_DTTM,
        lpc.PRODUCT_CATEGORY_RK AS LOB_RK,
        e.PROCESSED_DTTM
    FROM extracted e
    LEFT JOIN lookup_insurance_policy lip ON lip.POLICY_NO = e.POLICY_NO
    LEFT JOIN lookup_proposal lp ON lp.PROPOSAL_NO = e.PROPOSAL_NO
    LEFT JOIN lookup_coverage lc ON lc.COVERAGE_CD = e.X_COVERAGE_CD
    LEFT JOIN lookup_product_category lpc ON lpc.PRODUCT_CATEGORY_CD = e.PRODUCT_CATEGORY_CD
),
with_valid_from AS (
    SELECT
        *,
        COALESCE(
            DATEADD('SECOND', COALESCE(X_POLICY_VERSION, 0), CHANGE_EFFECTIVE_FROM_DTTM),
            CURRENT_TIMESTAMP()
        ) AS VALID_FROM_DTTM
    FROM with_lookups
),
with_valid_to AS (
    SELECT
        *,
        COALESCE(
            LEAD(VALID_FROM_DTTM) OVER (
                PARTITION BY POLICY_RK, X_POLICY_PROPOSAL_RK, X_ORDER_CD, COVERAGE_RIDER_RK
                ORDER BY VALID_FROM_DTTM
            ) - INTERVAL '1 SECOND',
            '5999-01-01 00:00:00'::TIMESTAMP_NTZ
        ) AS VALID_TO_DTTM
    FROM with_valid_from
),
with_surrogate AS (
    SELECT
        DENSE_RANK() OVER (
            ORDER BY POLICY_RK, X_POLICY_PROPOSAL_RK, X_ORDER_CD, COVERAGE_RIDER_RK
        ) AS UOE_RK,
        *
    FROM with_valid_to
),
final AS (
    SELECT
        UOE_RK,
        VALID_FROM_DTTM,
        POLICY_RK,
        X_POLICY_PROPOSAL_RK,
        X_POLICY_VERSION,
        X_ORDER_CD,
        NULL::NUMBER(12,0) AS INSURED_RK,
        COVERAGE_RIDER_RK,
        NULL::NUMBER(3,0) AS EQUIVALENT_AGE,
        NULL::VARCHAR(3) AS LIFE_HAZARD_CD,
        NULL::VARCHAR(3) AS LIFE_COVERAGE_STATUS_CD,
        NULL::VARCHAR(3) AS PURPOSE_CD,
        X_ADMISSION_DT,
        EFFECTIVE_DT,
        EXPIRATION_DT,
        RENEWABLE_IND,
        X_ORDER_STATUS,
        X_ORDER_STATUS_DT,
        NULL::NUMBER(9,4) AS GUAR_INT_RT,
        NULL::VARCHAR(3) AS PAYMENT_MODE_CD,
        CASH_VALUE,
        NULL::NUMBER(18,5) AS SURRENDER_CHARGE_AMT,
        NULL::NUMBER(18,5) AS CURR_AMT,
        NULL::NUMBER(18,5) AS VALUE_PER_UNIT,
        NULL::NUMBER(9,0) AS NO_OF_UNITS,
        NULL::NUMBER(18,5) AS BASE_PREMIUM_AMT,
        NULL::NUMBER(18,5) AS MODAL_PREMIUM_AMT,
        ANNUAL_PREMIUM_AMT,
        X_INDEXATION_RT,
        NULL::NUMBER(18,5) AS GDB_PREMIUM_AMT,
        NULL::NUMBER(18,5) AS COMMISSION_AMT,
        NULL::DATE AS TERMINATION_DT,
        NULL::NUMBER(18,5) AS TEMP_EXTRA_PREMIUM_AMT,
        NULL::DATE AS TEMP_EXTRA_START_DT,
        NULL::DATE AS TEMP_EXTRA_END_DT,
        NULL::NUMBER(18,5) AS PERM_EXTRA_PREMIUM_AMT,
        NULL::DATE AS PERM_EXTRA_START_DT,
        NULL::VARCHAR(1) AS ISSUED_AS_APPLIED_IND,
        NULL::NUMBER(18,5) AS PREMIUM_PER_UNIT,
        NULL::VARCHAR(3) AS RESERVE_METHOD_CD,
        NULL::NUMBER(18,5) AS RESERVE_AMT,
        NULL::NUMBER(9,4) AS RESERVE_INTEREST_RT,
        NULL::VARCHAR(3) AS BENEFIT_PERIOD_CD,
        NULL::VARCHAR(3) AS BENEFIT_MODE_CD,
        NULL::VARCHAR(3) AS WAITING_PERIOD_CD,
        NULL::DATE AS BENEFIT_AMT_REVISION_NEXT_DT,
        NULL::VARCHAR(3) AS JOINT_BENEFIT_PAYOUT_CD,
        NULL::DATE AS LAST_VALUATION_DT,
        NULL::VARCHAR(3) AS LIVES_TYPE_CD,
        NULL::DATE AS PREMIUM_TERMINATION_DT,
        NULL::NUMBER(18,5) AS BENEFIT_AMT,
        NULL::DATE AS BONUS_PAID_UP_TO_DT,
        NULL::NUMBER(18,5) AS BONUS_AMT,
        NULL::NUMBER(18,5) AS MATURITY_BENEFIT_AMT,
        NULL::DATE AS PREMIUM_PAID_UP_TO_DT,
        NULL::VARCHAR(1) AS RETURN_OF_PREM_BENEFIT_FLG,
        NULL::NUMBER(9,4) AS RETURN_OF_PREM_RT,
        X_POLICY_STATUS_CD,
        X_POLICY_TERMINATION_DT,
        NULL::NUMBER(9,4) AS SALARY_PCT,
        NULL::VARCHAR(3) AS SOLVENCY2_LEVEL_1_SEGMENT_CD,
        NULL::VARCHAR(3) AS SOLVENCY2_LEVEL_2_SEGMENT_CD,
        LOB_RK,
        CHANGE_EFFECTIVE_FROM_DTTM,
        CHANGE_EFFECTIVE_TO_DTTM,
        NULL::NUMBER(12,0) AS JOINT_LIFE_INSURED_RK,
        VALID_TO_DTTM,
        PROCESSED_DTTM,
        MD5_HEX(
            COALESCE(TO_VARCHAR(X_POLICY_VERSION), '') ||
            COALESCE(TO_VARCHAR(INSURED_RK), '') ||
            COALESCE(TO_VARCHAR(EQUIVALENT_AGE), '') ||
            COALESCE(LIFE_HAZARD_CD, '') ||
            COALESCE(LIFE_COVERAGE_STATUS_CD, '') ||
            COALESCE(PURPOSE_CD, '') ||
            COALESCE(TO_VARCHAR(X_ADMISSION_DT), '') ||
            COALESCE(TO_VARCHAR(EFFECTIVE_DT), '') ||
            COALESCE(TO_VARCHAR(EXPIRATION_DT), '') ||
            COALESCE(RENEWABLE_IND, '') ||
            COALESCE(X_ORDER_STATUS, '') ||
            COALESCE(TO_VARCHAR(X_ORDER_STATUS_DT), '') ||
            COALESCE(TO_VARCHAR(GUAR_INT_RT), '') ||
            COALESCE(PAYMENT_MODE_CD, '') ||
            COALESCE(TO_VARCHAR(CASH_VALUE), '') ||
            COALESCE(TO_VARCHAR(SURRENDER_CHARGE_AMT), '') ||
            COALESCE(TO_VARCHAR(CURR_AMT), '') ||
            COALESCE(TO_VARCHAR(VALUE_PER_UNIT), '') ||
            COALESCE(TO_VARCHAR(NO_OF_UNITS), '') ||
            COALESCE(TO_VARCHAR(BASE_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(MODAL_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(ANNUAL_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(X_INDEXATION_RT), '') ||
            COALESCE(TO_VARCHAR(GDB_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(COMMISSION_AMT), '') ||
            COALESCE(TO_VARCHAR(TERMINATION_DT), '') ||
            COALESCE(TO_VARCHAR(TEMP_EXTRA_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(TEMP_EXTRA_START_DT), '') ||
            COALESCE(TO_VARCHAR(TEMP_EXTRA_END_DT), '') ||
            COALESCE(TO_VARCHAR(PERM_EXTRA_PREMIUM_AMT), '') ||
            COALESCE(TO_VARCHAR(PERM_EXTRA_START_DT), '') ||
            COALESCE(ISSUED_AS_APPLIED_IND, '') ||
            COALESCE(TO_VARCHAR(PREMIUM_PER_UNIT), '') ||
            COALESCE(RESERVE_METHOD_CD, '') ||
            COALESCE(TO_VARCHAR(RESERVE_AMT), '') ||
            COALESCE(TO_VARCHAR(RESERVE_INTEREST_RT), '') ||
            COALESCE(BENEFIT_PERIOD_CD, '') ||
            COALESCE(BENEFIT_MODE_CD, '') ||
            COALESCE(WAITING_PERIOD_CD, '') ||
            COALESCE(TO_VARCHAR(BENEFIT_AMT_REVISION_NEXT_DT), '') ||
            COALESCE(JOINT_BENEFIT_PAYOUT_CD, '') ||
            COALESCE(TO_VARCHAR(LAST_VALUATION_DT), '') ||
            COALESCE(LIVES_TYPE_CD, '') ||
            COALESCE(TO_VARCHAR(PREMIUM_TERMINATION_DT), '') ||
            COALESCE(TO_VARCHAR(BENEFIT_AMT), '') ||
            COALESCE(TO_VARCHAR(BONUS_PAID_UP_TO_DT), '') ||
            COALESCE(TO_VARCHAR(BONUS_AMT), '') ||
            COALESCE(TO_VARCHAR(MATURITY_BENEFIT_AMT), '') ||
            COALESCE(TO_VARCHAR(PREMIUM_PAID_UP_TO_DT), '') ||
            COALESCE(RETURN_OF_PREM_BENEFIT_FLG, '') ||
            COALESCE(TO_VARCHAR(RETURN_OF_PREM_RT), '') ||
            COALESCE(X_POLICY_STATUS_CD, '') ||
            COALESCE(TO_VARCHAR(X_POLICY_TERMINATION_DT), '') ||
            COALESCE(TO_VARCHAR(SALARY_PCT), '') ||
            COALESCE(SOLVENCY2_LEVEL_1_SEGMENT_CD, '') ||
            COALESCE(SOLVENCY2_LEVEL_2_SEGMENT_CD, '') ||
            COALESCE(TO_VARCHAR(LOB_RK), '') ||
            COALESCE(TO_VARCHAR(CHANGE_EFFECTIVE_FROM_DTTM), '') ||
            COALESCE(TO_VARCHAR(CHANGE_EFFECTIVE_TO_DTTM), '') ||
            COALESCE(TO_VARCHAR(JOINT_LIFE_INSURED_RK), '')
        ) AS DIGEST_VALUE
    FROM with_surrogate
)
SELECT
    UOE_RK,
    VALID_FROM_DTTM,
    POLICY_RK,
    X_POLICY_PROPOSAL_RK,
    X_POLICY_VERSION,
    X_ORDER_CD,
    INSURED_RK,
    COVERAGE_RIDER_RK,
    EQUIVALENT_AGE,
    LIFE_HAZARD_CD,
    LIFE_COVERAGE_STATUS_CD,
    PURPOSE_CD,
    X_ADMISSION_DT,
    EFFECTIVE_DT,
    EXPIRATION_DT,
    RENEWABLE_IND,
    X_ORDER_STATUS,
    X_ORDER_STATUS_DT,
    GUAR_INT_RT,
    PAYMENT_MODE_CD,
    CASH_VALUE,
    SURRENDER_CHARGE_AMT,
    CURR_AMT,
    VALUE_PER_UNIT,
    NO_OF_UNITS,
    BASE_PREMIUM_AMT,
    MODAL_PREMIUM_AMT,
    ANNUAL_PREMIUM_AMT,
    X_INDEXATION_RT,
    GDB_PREMIUM_AMT,
    COMMISSION_AMT,
    TERMINATION_DT,
    TEMP_EXTRA_PREMIUM_AMT,
    TEMP_EXTRA_START_DT,
    TEMP_EXTRA_END_DT,
    PERM_EXTRA_PREMIUM_AMT,
    PERM_EXTRA_START_DT,
    ISSUED_AS_APPLIED_IND,
    PREMIUM_PER_UNIT,
    RESERVE_METHOD_CD,
    RESERVE_AMT,
    RESERVE_INTEREST_RT,
    BENEFIT_PERIOD_CD,
    BENEFIT_MODE_CD,
    WAITING_PERIOD_CD,
    BENEFIT_AMT_REVISION_NEXT_DT,
    JOINT_BENEFIT_PAYOUT_CD,
    LAST_VALUATION_DT,
    LIVES_TYPE_CD,
    PREMIUM_TERMINATION_DT,
    BENEFIT_AMT,
    BONUS_PAID_UP_TO_DT,
    BONUS_AMT,
    MATURITY_BENEFIT_AMT,
    PREMIUM_PAID_UP_TO_DT,
    RETURN_OF_PREM_BENEFIT_FLG,
    RETURN_OF_PREM_RT,
    X_POLICY_STATUS_CD,
    X_POLICY_TERMINATION_DT,
    SALARY_PCT,
    SOLVENCY2_LEVEL_1_SEGMENT_CD,
    SOLVENCY2_LEVEL_2_SEGMENT_CD,
    LOB_RK,
    CHANGE_EFFECTIVE_FROM_DTTM,
    CHANGE_EFFECTIVE_TO_DTTM,
    JOINT_LIFE_INSURED_RK,
    VALID_TO_DTTM,
    PROCESSED_DTTM,
    DIGEST_VALUE
FROM final;
