------------------------------------------------------------
-- LOAD: LifePolicyTrans (Splitter Pattern)
-- Source: CAVIDA_POC.STAGING.INSPOL_LIFEPOLICYTRANS_003
-- Lookups: CAVIDA_POC.POC_LOOK.{EMPLOYEE, X_BUSINESS_STRUCTURE, INSURANCE_POLICY}
-- Target 1: CAVIDA_POC.DW.X_LIFE_POLICY_TRANS_HIST (APPEND closed rows)
-- Target 2: CAVIDA_POC.DW.LIFE_POLICY_TRANS (REPLACE with open rows)
------------------------------------------------------------

-- Statement 1: Append closed rows (X_IS_CLOSED_FLG = 'Y') to history table
INSERT INTO CAVIDA_POC.DW.X_LIFE_POLICY_TRANS_HIST (
    POLICY_TRANS_ID,
    SOURCE_SYSTEM_CD,
    POLICY_RK,
    ORIGINAL_POLICY_TRANS_ID,
    X_MOV_DT,
    TRANS_DT,
    X_VALUE_DT,
    X_EMISSION_DT,
    X_CREATION_DT,
    X_PROCESSED_DT,
    X_REGULARIZATION_DT,
    TRANS_TYPE_CD,
    TRANS_SUB_TYPE_CD,
    REVERSAL_IND,
    TRANS_FEE,
    TRANS_GROSS_AMT,
    TRANS_NET_AMT,
    X_TRANS_PURE_AMT,
    TRANS_CURRENCY_CD,
    REFERENCE_NO,
    PAYMENT_METHOD_CD,
    TOTAL_UNITS,
    UNIT_VALUE,
    FEDERAL_TAX_WITHHELD,
    JURISDICTION_TAX_WITHHELD,
    LOCAL_TAX_WITHHELD,
    SERVICES_TAX_WITHHELD,
    ANNUITY_CONTRIBUTION_AMT,
    SUB_ACCOUNT_RK,
    USER_CD,
    PAYEE_RK,
    X_TRANS_PREVIOUS_STATUS_CD,
    X_CANCEL_REASON_CD,
    X_CANCEL_DT,
    X_TRANS_STATUS_CD,
    X_PERIOD_FROM_DT,
    X_PERIOD_TO_DT,
    X_INEM_AMT,
    X_SUBS_CHARGE_AMT,
    X_SUBS_FEE_AMT,
    X_MANAGEMENT_FEE_AMT,
    X_EXIT_DT,
    X_RETURNED_DT,
    X_REINVESTMENT_FLG,
    X_RET_REASON_CD,
    X_IS_CLOSED_FLG,
    X_EMPLOYEE_RK,
    X_BSN_STRUCTURE_RK,
    X_PROCESSED_FLG,
    PROCESSED_DTTM,
    X_CHARGEBACK_FLG,
    X_RESULT_PARTICIPATION_FLG,
    X_POLICY_TRANS_MANUAL_FLG
)
SELECT
    s.POLICY_TRANS_ID,
    'Db2'                                   AS SOURCE_SYSTEM_CD,
    ip.POLICY_RK,
    s.ORIGINAL_POLICY_TRANS_ID,
    s.X_MOV_DT,
    s.TRANS_DT,
    s.X_VALUE_DT,
    s.X_EMISSION_DT,
    s.X_CREATION_DT,
    s.X_PROCESSED_DT,
    s.X_REGULARIZATION_DT,
    'PPRM'                                  AS TRANS_TYPE_CD,
    s.TRANS_SUB_TYPE_CD,
    NULL                                    AS REVERSAL_IND,
    NULL                                    AS TRANS_FEE,
    s.TRANS_GROSS_AMT,
    s.TRANS_NET_AMT,
    s.X_TRANS_PURE_AMT,
    NULL                                    AS TRANS_CURRENCY_CD,
    NULL                                    AS REFERENCE_NO,
    s.PAYMENT_METHOD_CD,
    NULL                                    AS TOTAL_UNITS,
    NULL                                    AS UNIT_VALUE,
    NULL                                    AS FEDERAL_TAX_WITHHELD,
    NULL                                    AS JURISDICTION_TAX_WITHHELD,
    NULL                                    AS LOCAL_TAX_WITHHELD,
    NULL                                    AS SERVICES_TAX_WITHHELD,
    NULL                                    AS ANNUITY_CONTRIBUTION_AMT,
    NULL                                    AS SUB_ACCOUNT_RK,
    NULL                                    AS USER_CD,
    NULL                                    AS PAYEE_RK,
    s.X_TRANS_PREVIOUS_STATUS_CD,
    s.X_CANCEL_REASON_CD,
    s.X_CANCEL_DT,
    s.X_TRANS_STATUS_CD,
    s.X_PERIOD_FROM_DT,
    s.X_PERIOD_TO_DT,
    s.X_INEM_AMT,
    s.X_SUBS_CHARGE_AMT,
    s.X_SUBS_FEE_AMT,
    s.X_MANAGEMENT_FEE_AMT,
    s.X_EXIT_DT,
    s.X_RETURNED_DT,
    s.X_REINVESTMENT_FLG,
    s.X_RET_REASON_CD,
    s.X_IS_CLOSED_FLG,
    emp.EMPLOYEE_RK                         AS X_EMPLOYEE_RK,
    COALESCE(bs.BSN_STRUCTURE_RK, ip.BSN_STRUCTURE_RK)
                                            AS X_BSN_STRUCTURE_RK,
    s.X_PROCESSED_FLG,
    CURRENT_TIMESTAMP()                     AS PROCESSED_DTTM,
    s.X_CHARGEBACK_FLG,
    s.X_RESULT_PARTICIPATION_FLG,
    s.X_POLICY_TRANS_MANUAL_FLG
FROM CAVIDA_POC.STAGING.INSPOL_LIFEPOLICYTRANS_003 s
LEFT JOIN (
    SELECT X_EMPLOYEE_EXT_ID, EMPLOYEE_RK
    FROM CAVIDA_POC.POC_LOOK.EMPLOYEE
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) emp
    ON s.X_EMPLOYEE_EXT_ID = emp.X_EMPLOYEE_EXT_ID
LEFT JOIN (
    SELECT AGENCY_INT_ID, BSN_STRUCTURE_RK
    FROM CAVIDA_POC.POC_LOOK.X_BUSINESS_STRUCTURE
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) bs
    ON s.AGENCY_INT_ID = bs.AGENCY_INT_ID
LEFT JOIN (
    SELECT POLICY_NO, POLICY_RK, X_BSN_STRUCTURE_RK AS BSN_STRUCTURE_RK
    FROM CAVIDA_POC.POC_LOOK.INSURANCE_POLICY
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) ip
    ON s.POLICY_NO = ip.POLICY_NO
WHERE s.X_IS_CLOSED_FLG = 'Y'
;


-- Statement 2: Replace open rows (X_IS_CLOSED_FLG = 'N') into LIFE_POLICY_TRANS
CREATE OR REPLACE TABLE CAVIDA_POC.DW.LIFE_POLICY_TRANS AS
SELECT
    s.POLICY_TRANS_ID,
    'Db2'                                   AS SOURCE_SYSTEM_CD,
    ip.POLICY_RK,
    s.ORIGINAL_POLICY_TRANS_ID,
    s.X_MOV_DT,
    s.TRANS_DT,
    s.X_VALUE_DT,
    s.X_EMISSION_DT,
    s.X_CREATION_DT,
    s.X_PROCESSED_DT,
    s.X_REGULARIZATION_DT,
    'PPRM'                                  AS TRANS_TYPE_CD,
    s.TRANS_SUB_TYPE_CD,
    NULL::VARCHAR(1)                        AS REVERSAL_IND,
    NULL::NUMBER(18,5)                      AS TRANS_FEE,
    s.TRANS_GROSS_AMT,
    s.TRANS_NET_AMT,
    s.X_TRANS_PURE_AMT,
    NULL::VARCHAR(3)                        AS TRANS_CURRENCY_CD,
    NULL::VARCHAR(32)                       AS REFERENCE_NO,
    s.PAYMENT_METHOD_CD,
    NULL::NUMBER                            AS TOTAL_UNITS,
    NULL::NUMBER(18,5)                      AS UNIT_VALUE,
    NULL::NUMBER(18,5)                      AS FEDERAL_TAX_WITHHELD,
    NULL::NUMBER(18,5)                      AS JURISDICTION_TAX_WITHHELD,
    NULL::NUMBER(18,5)                      AS LOCAL_TAX_WITHHELD,
    NULL::NUMBER(18,5)                      AS SERVICES_TAX_WITHHELD,
    NULL::NUMBER(18,5)                      AS ANNUITY_CONTRIBUTION_AMT,
    NULL::NUMBER                            AS SUB_ACCOUNT_RK,
    NULL::VARCHAR(3)                        AS USER_CD,
    NULL::NUMBER                            AS PAYEE_RK,
    s.X_TRANS_PREVIOUS_STATUS_CD,
    s.X_CANCEL_REASON_CD,
    s.X_CANCEL_DT,
    s.X_TRANS_STATUS_CD,
    s.X_PERIOD_FROM_DT,
    s.X_PERIOD_TO_DT,
    s.X_INEM_AMT,
    s.X_SUBS_CHARGE_AMT,
    s.X_SUBS_FEE_AMT,
    s.X_MANAGEMENT_FEE_AMT,
    s.X_EXIT_DT,
    s.X_RETURNED_DT,
    s.X_REINVESTMENT_FLG,
    s.X_RET_REASON_CD,
    s.X_IS_CLOSED_FLG,
    emp.EMPLOYEE_RK                         AS X_EMPLOYEE_RK,
    COALESCE(bs.BSN_STRUCTURE_RK, ip.BSN_STRUCTURE_RK)
                                            AS X_BSN_STRUCTURE_RK,
    s.X_PROCESSED_FLG,
    CURRENT_TIMESTAMP()                     AS PROCESSED_DTTM,
    s.X_CHARGEBACK_FLG,
    s.X_RESULT_PARTICIPATION_FLG,
    s.X_POLICY_TRANS_MANUAL_FLG
FROM CAVIDA_POC.STAGING.INSPOL_LIFEPOLICYTRANS_003 s
LEFT JOIN (
    SELECT X_EMPLOYEE_EXT_ID, EMPLOYEE_RK
    FROM CAVIDA_POC.POC_LOOK.EMPLOYEE
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) emp
    ON s.X_EMPLOYEE_EXT_ID = emp.X_EMPLOYEE_EXT_ID
LEFT JOIN (
    SELECT AGENCY_INT_ID, BSN_STRUCTURE_RK
    FROM CAVIDA_POC.POC_LOOK.X_BUSINESS_STRUCTURE
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) bs
    ON s.AGENCY_INT_ID = bs.AGENCY_INT_ID
LEFT JOIN (
    SELECT POLICY_NO, POLICY_RK, X_BSN_STRUCTURE_RK AS BSN_STRUCTURE_RK
    FROM CAVIDA_POC.POC_LOOK.INSURANCE_POLICY
    WHERE VALID_FROM_DTTM <= CURRENT_TIMESTAMP()
      AND VALID_TO_DTTM   >= CURRENT_TIMESTAMP()
) ip
    ON s.POLICY_NO = ip.POLICY_NO
WHERE s.X_IS_CLOSED_FLG = 'N'
;
