-- =============================================================================
-- CA Vida POC - Extraction Layer (COPY INTO)
-- =============================================================================
-- Parallel ingestion of 17 CSV files from stage into transient tables.
-- Each table maps to a source DB2/SAS table.
-- Total data: ~190M rows across 17 tables.
-- =============================================================================

USE WAREHOUSE CAVIDA_POC_WH;
USE SCHEMA CAVIDA_POC.EXTRACTION;
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- Create transient extraction tables + COPY INTO (all 17 in parallel)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. ACTA00 (Accounting transactions - 11.4M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_ACTA00_POC (
    A0$COB NUMBER(7,0), A0$CON NUMBER(7,0), A0SEQS NUMBER(6,0), A0ASAI NUMBER(5,0),
    A0MSAI NUMBER(3,0), A0DSAI NUMBER(3,0), A0SEQE NUMBER(6,0), A0MOVE NUMBER(8,0),
    A0AENT NUMBER(5,0), A0MENT NUMBER(3,0), A0DENT NUMBER(3,0), A0ADEV NUMBER(5,0),
    A0MDEV NUMBER(3,0), A0DDEV NUMBER(3,0), A0TIPO VARCHAR(2), A0CRED VARCHAR(1),
    A0VALOR NUMBER(15,2), A0CUST NUMBER(15,2), A0VAL1 NUMBER(12,0), A0VAL2 NUMBER(12,0),
    A0$MOD NUMBER(3,0), A0$APL NUMBER(9,0), A0$REC NUMBER(9,0), A0$PRO VARCHAR(2),
    A0BANC NUMBER(7,0), A0NVER NUMBER(3,0), A0INF1 VARCHAR(1), A0INF2 VARCHAR(1),
    A0INF3 VARCHAR(1), A0INF4 VARCHAR(1), A0INF5 VARCHAR(1), A0INF6 VARCHAR(1),
    A0INF7 VARCHAR(1), A0INF8 VARCHAR(1), A0INF9 VARCHAR(1), A0INFA VARCHAR(1),
    A0INFB VARCHAR(1), A0INFC VARCHAR(2), A0$ENT NUMBER(9,0), A0AALT NUMBER(5,0),
    A0MALT NUMBER(3,0), A0DALT NUMBER(3,0), A0USER VARCHAR(10), A0MOED VARCHAR(3),
    A0IDPR NUMBER(7,0), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract ACTA00: ~11.4M rows | 45 cols';

COPY INTO DB2_ACTA00_POC
FROM @INPUT_DATA/ACTA00/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 2. ACTA03 (Accounting details - 11M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_ACTA03_POC (
    A3$COB NUMBER(7,0), A3$CON NUMBER(7,0), A3SEQS NUMBER(6,0), A3ASAI NUMBER(5,0),
    A3MSAI NUMBER(3,0), A3DSAI NUMBER(3,0), A3SEQE NUMBER(6,0), A3MOVE NUMBER(8,0),
    A3AENT NUMBER(5,0), A3MENT NUMBER(3,0), A3DENT NUMBER(3,0), A3TIPO VARCHAR(2),
    A3NCON VARCHAR(14), A3CRED VARCHAR(1), A3TIPV NUMBER(3,0), A3VALOR NUMBER(15,2),
    A3CAPI NUMBER(15,2), A3$MOD NUMBER(3,0), A3$APL NUMBER(9,0), A3NVER NUMBER(3,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract ACTA03: ~11M rows | 21 cols';

COPY INTO DB2_ACTA03_POC
FROM @INPUT_DATA/ACTA03/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 3. ACTA0P (Accounting parameters - 245K rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_ACTA0P_POC (
    AP$COB NUMBER(7,0), AP$CON NUMBER(7,0), APSEQS NUMBER(6,0), APASAI NUMBER(5,0),
    APMSAI NUMBER(3,0), APDSAI NUMBER(3,0), APSEQE NUMBER(6,0), APMOVE NUMBER(8,0),
    APAENT NUMBER(5,0), APMENT NUMBER(3,0), APDENT NUMBER(3,0), APSITU VARCHAR(4),
    APTIPO VARCHAR(2), APINDI VARCHAR(1), APVALO NUMBER(15,2), APDURA NUMBER(6,0),
    AP$MOD NUMBER(3,0), AP$APL NUMBER(9,0), APNVER NUMBER(3,0), APFALT NUMBER(5,0),
    APMALT NUMBER(3,0), APDALT NUMBER(3,0), APUSER VARCHAR(10)
) COMMENT = 'Extract ACTA0P: ~245K rows | 23 cols (no PROCESSED_DTTM)';

COPY INTO DB2_ACTA0P_POC
FROM @INPUT_DATA/ACTA0P/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 4. APOL00 (Policies - 1.4M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_APOL00_POC (
    AP$MOD NUMBER(3,0), AP$APL NUMBER(9,0), APNVER NUMBER(3,0), APAAPL NUMBER(5,0),
    APMAPL NUMBER(3,0), APDAPL NUMBER(3,0), APAINI NUMBER(5,0), APMINI NUMBER(3,0),
    APDINI NUMBER(3,0), APAFIM NUMBER(5,0), APMFIM NUMBER(3,0), APDFIM NUMBER(3,0),
    APDURE NUMBER(3,0), APSTAT VARCHAR(1), APTYPE VARCHAR(1), APNPRO VARCHAR(14),
    APNPRT VARCHAR(14), APSEXO VARCHAR(1), APIDAD NUMBER(3,0), APNAPE VARCHAR(14),
    AP$BAN NUMBER(5,0), APBANC NUMBER(7,0), APAGPA NUMBER(7,0), APCMOD NUMBER(3,0),
    APCAMP VARCHAR(8), APNPAG NUMBER(3,0), APFPAG VARCHAR(1), APFREC VARCHAR(1),
    APINIC VARCHAR(1), AP$ENT NUMBER(9,0), AP$EN2 NUMBER(9,0), APDANG NUMBER(3,0),
    APCAPO NUMBER(14,2), APCAPI NUMBER(14,2), APPREM NUMBER(14,2), APPREI NUMBER(14,2),
    APCOMR NUMBER(14,2), APCOMD NUMBER(14,2), APCOME NUMBER(14,2), APVAEX NUMBER(14,2),
    APSOBR NUMBER(14,2), APENCI NUMBER(14,2), APGARL NUMBER(14,2), APGARP NUMBER(14,2),
    APVRES NUMBER(14,2), APUTIL NUMBER(14,2), APDEDU NUMBER(14,2), APAINC NUMBER(5,0),
    APMINC NUMBER(3,0), APDINC NUMBER(3,0), APINDX NUMBER(7,4), APMOED VARCHAR(3),
    APAALT NUMBER(5,0), APMALT NUMBER(3,0), APDALT NUMBER(3,0), APUSER VARCHAR(10),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract APOL00: ~1.4M rows | 55 cols';

COPY INTO DB2_APOL00_POC
FROM @INPUT_DATA/APOL00/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 5. APOL03 (Policy details - 1.1M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_APOL03_POC (
    AB$MOD NUMBER(3,0), AB$APL NUMBER(9,0), ABNVER NUMBER(3,0), ABNCON VARCHAR(14),
    ABSEXO VARCHAR(1), ABIDAD NUMBER(3,0), ABTIPO VARCHAR(2), ABCAPI NUMBER(14,2),
    ABPREM NUMBER(14,2), ABSOBR NUMBER(14,2), ABGARL NUMBER(14,2), ABGARP NUMBER(14,2),
    ABVRES NUMBER(14,2), ABUTIL NUMBER(14,2), ABFCOB NUMBER(3,0), ABDURE NUMBER(3,0),
    ABSTAT VARCHAR(1), ABINDX NUMBER(7,4), ABAALT NUMBER(5,0), ABMALT NUMBER(3,0),
    ABDALT NUMBER(3,0), ABUSER VARCHAR(10), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract APOL03: ~1.1M rows | 23 cols';

COPY INTO DB2_APOL03_POC
FROM @INPUT_DATA/APOL03/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 6. APOL0PH (Policy history - 142K rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_APOL0PH_POC (
    PH$MOD NUMBER(3,0), PH$APL NUMBER(9,0), PHNVER NUMBER(3,0), PHAINI NUMBER(5,0),
    PHMINI NUMBER(3,0), PHDINI NUMBER(3,0), PHAFIM NUMBER(5,0), PHMFIM NUMBER(3,0),
    PHDFIM NUMBER(3,0), PHSTAT VARCHAR(1), PHAALT NUMBER(5,0), PHMALT NUMBER(3,0),
    PHDALT NUMBER(3,0), PHUSER VARCHAR(10), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract APOL0PH: ~142K rows | 15 cols';

COPY INTO DB2_APOL0PH_POC
FROM @INPUT_DATA/APOL0PH/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 7. APOL0P (Policy parameters - 12.5K rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_APOL0P_POC (
    PP$MOD NUMBER(3,0), PP$APL NUMBER(9,0), PPNVER NUMBER(3,0), PPASAI NUMBER(5,0),
    PPMSAI NUMBER(3,0), PPDSAI NUMBER(3,0), PPSITU VARCHAR(4), PPAINC NUMBER(5,0),
    PPMINC NUMBER(3,0), PPDINC NUMBER(3,0), PPINDX NUMBER(7,4), PPFREC VARCHAR(1),
    PPFPAG VARCHAR(1), PPNPAG NUMBER(3,0), PPAALT NUMBER(5,0), PPMALT NUMBER(3,0),
    PPDALT NUMBER(3,0), PPUSER VARCHAR(10), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract APOL0P: ~12.5K rows | 19 cols';

COPY INTO DB2_APOL0P_POC
FROM @INPUT_DATA/APOL0P/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 8. APOLPA (Policy-person links - 8.5M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_APOLPA_POC (
    PA$MOD NUMBER(3,0), PA$APL NUMBER(9,0), PANVER NUMBER(3,0), PA$ENT NUMBER(9,0),
    PATIPO VARCHAR(2), PAPAPEL VARCHAR(1), PASTAT VARCHAR(1), PAAALT NUMBER(5,0),
    PAMALT NUMBER(3,0), PADALT NUMBER(3,0), PAUSER VARCHAR(10),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract APOLPA: ~8.5M rows | 12 cols';

COPY INTO DB2_APOLPA_POC
FROM @INPUT_DATA/APOLPA/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 9. ENTREL (Entity relations - 2.2M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_ENTREL_POC (
    ER$EN1 NUMBER(9,0), ERREL VARCHAR(2), ER$EN2 NUMBER(9,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract ENTREL: ~2.2M rows | 4 cols';

COPY INTO DB2_ENTREL_POC
FROM @INPUT_DATA/ENTREL/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 10. ENTVIN (Entity links - 8M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_ENTVIN_POC (
    EV$ENT NUMBER(9,0), EVTIPO VARCHAR(1), EVNCON VARCHAR(14), EVEMIS VARCHAR(3),
    EVAINC NUMBER(5,0), EVMINC NUMBER(3,0), EVDINC NUMBER(3,0), EVFVAL NUMBER(5,0),
    EVMVAL NUMBER(3,0), EVDVAL NUMBER(3,0), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract ENTVIN: ~8M rows | 11 cols';

COPY INTO DB2_ENTVIN_POC
FROM @INPUT_DATA/ENTVIN/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 11. EVENTO (Events - 45.6M rows - LARGEST extraction)
CREATE OR REPLACE TRANSIENT TABLE DB2_EVENTO_POC (
    EE$MOD NUMBER(3,0), EE$APL NUMBER(9,0), EENVER NUMBER(3,0), EEMOVE NUMBER(8,0),
    EEASAI NUMBER(5,0), EEMSAI NUMBER(3,0), EEDSAI NUMBER(3,0), EETIPO VARCHAR(2),
    EEVALO NUMBER(15,2), EE$ENT NUMBER(9,0), EENCON VARCHAR(14), EESITU VARCHAR(4),
    EEBANC NUMBER(7,0), EEINF1 VARCHAR(1), EEINF2 VARCHAR(1), EEINF3 VARCHAR(1),
    EEINF4 VARCHAR(1), EEINF5 VARCHAR(1), EEAALT NUMBER(5,0), EEMALT NUMBER(3,0),
    EEDALT NUMBER(3,0), EEUSER VARCHAR(10), EEMOED VARCHAR(3), EEIDPR NUMBER(7,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract EVENTO: ~45.6M rows | 25 cols';

COPY INTO DB2_EVENTO_POC
FROM @INPUT_DATA/EVENTO/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 12. MOPEC1 (Movement details - 12.1M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_MOPEC1_POC (
    M1$MOV VARCHAR(10), M1$COB NUMBER(7,0), M1$CON NUMBER(7,0), M1SEQS NUMBER(6,0),
    M1ASAI NUMBER(5,0), M1MSAI NUMBER(3,0), M1DSAI NUMBER(3,0), M1SEQE NUMBER(6,0),
    M1MOVE NUMBER(8,0), M1AENT NUMBER(5,0), M1MENT NUMBER(3,0), M1DENT NUMBER(3,0),
    M1TIPV NUMBER(3,0), M1VALO NUMBER(15,2), M1CAPI NUMBER(15,2), M1$MOD NUMBER(3,0),
    M1$APL NUMBER(9,0), M1NVER NUMBER(3,0), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract MOPEC1: ~12.1M rows | 19 cols';

COPY INTO DB2_MOPEC1_POC
FROM @INPUT_DATA/MOPEC1/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 13. MOVIML (Movements - 27.9M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_MOVIML_POC (
    ML$MOV VARCHAR(10), ML$COB NUMBER(7,0), ML$CON NUMBER(7,0), MLSEQS NUMBER(6,0),
    MLASAI NUMBER(5,0), MLMSAI NUMBER(3,0), MLDSAI NUMBER(3,0), MLSEQE NUMBER(6,0),
    MLMOVE NUMBER(8,0), MLAENT NUMBER(5,0), MLMENT NUMBER(3,0), MLDENT NUMBER(3,0),
    MLADEV NUMBER(5,0), MLMDEV NUMBER(3,0), MLDDEV NUMBER(3,0), MLSITC VARCHAR(4),
    MLBANC NUMBER(7,0), ML$BAN NUMBER(5,0), ML$BAL NUMBER(5,0), MLNCON VARCHAR(14),
    MLVALO NUMBER(12,0), MLCUST NUMBER(12,0), MLVAL1 NUMBER(12,0), MLVAL2 NUMBER(12,0),
    ML$ENT NUMBER(9,0), ML$MOD NUMBER(3,0), MLNVER NUMBER(3,0), ML$APL NUMBER(9,0),
    MLNANO NUMBER(3,0), MLNMES NUMBER(3,0), MLNSEQ NUMBER(6,0), ML$RPR NUMBER(10,0),
    MLTDOC VARCHAR(1), MLSTAT VARCHAR(1), MLINF1 VARCHAR(1), MLINF2 VARCHAR(1),
    MLINF3 VARCHAR(1), MLINF4 VARCHAR(1), MLINF5 VARCHAR(1), MLINF6 VARCHAR(1),
    MLINF7 VARCHAR(1), MLINF8 VARCHAR(1), MLINF9 VARCHAR(1), MLINFA VARCHAR(1),
    MLINFB VARCHAR(2), MLINFC VARCHAR(2), MLAALT NUMBER(5,0), MLMALT NUMBER(3,0),
    MLDALT NUMBER(3,0), MLUSER VARCHAR(10), MLMOED VARCHAR(3), MLIDPR NUMBER(7,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract MOVIML: ~27.9M rows | 52 cols';

COPY INTO DB2_MOVIML_POC
FROM @INPUT_DATA/MOVIML/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 14. RECI0X (Receipts extra - 1.6M rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_RECI0X_POC (
    RX$REC NUMBER(9,0), RXDINV NUMBER(3,0), RXMINV NUMBER(3,0), RXAINV NUMBER(5,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract RECI0X: ~1.6M rows | 5 cols';

COPY INTO DB2_RECI0X_POC
FROM @INPUT_DATA/RECI0X/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 15. RECIBO (Receipts - 47.4M rows - uses special file format)
CREATE OR REPLACE TRANSIENT TABLE DB2_RECIBO_POC (
    RC$REC NUMBER(9,0), RC$MOD NUMBER(3,0), RC$APL NUMBER(9,0), RCNVER NUMBER(3,0),
    RCNCON VARCHAR(14), RCTIPO VARCHAR(2), RCSTAT VARCHAR(1), RCSTA3 VARCHAR(4),
    RCAEMI NUMBER(5,0), RCMEMI NUMBER(3,0), RCDEMI NUMBER(3,0), RCAVEN NUMBER(5,0),
    RCMVEN NUMBER(3,0), RCDVEN NUMBER(3,0), RCACOB NUMBER(5,0), RCMCOB NUMBER(3,0),
    RCDCOB NUMBER(3,0), RCAINI NUMBER(5,0), RCMINI NUMBER(3,0), RCDINI NUMBER(3,0),
    RCAFIM NUMBER(5,0), RCMFIM NUMBER(3,0), RCDFIM NUMBER(3,0), RCPREM NUMBER(14,2),
    RCENCI NUMBER(14,2), RCSOBR NUMBER(14,2), RCCOMR NUMBER(14,2), RCCOMD NUMBER(14,2),
    RCIMP1 NUMBER(14,2), RCIMP2 NUMBER(14,2), RCIMP3 NUMBER(14,2), RCVRES NUMBER(14,2),
    RC$BAN NUMBER(5,0), RCBANC NUMBER(7,0), RCNPAG NUMBER(3,0), RCFPAG VARCHAR(1),
    RCFREC VARCHAR(1), RC$ENT NUMBER(9,0), RCPAGA NUMBER(14,2), RCINF1 VARCHAR(1),
    RCINF2 VARCHAR(1), RCINF3 VARCHAR(1), RCIDPR NUMBER(7,0), RCSTAN NUMBER(3,0),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract RECIBO: ~47.4M rows | 45 cols (uses CSV_LATIN1_RECIBO format)';

COPY INTO DB2_RECIBO_POC
FROM @INPUT_DATA/RECIBO/
FILE_FORMAT = CSV_LATIN1_RECIBO
ON_ERROR = 'CONTINUE';

-- 16. RECPRO (Receipt processing - 256K rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_RECPRO_POC (
    RP$REC NUMBER(9,0), RP$MOD NUMBER(3,0), RP$APL NUMBER(9,0), RPNVER NUMBER(3,0),
    RPNCON VARCHAR(14), RPTIPV NUMBER(3,0), RPVALO NUMBER(15,2), RPCAPI NUMBER(15,2),
    PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract RECPRO: ~256K rows | 9 cols';

COPY INTO DB2_RECPRO_POC
FROM @INPUT_DATA/RECPRO/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- 17. RECREL (Receipt relations - 960K rows)
CREATE OR REPLACE TRANSIENT TABLE DB2_RECREL_POC (
    RR$REC NUMBER(9,0), RR$MOD NUMBER(3,0), RR$APL NUMBER(9,0), RRNVER NUMBER(3,0),
    RRNCON VARCHAR(14), RR$COB NUMBER(7,0), RR$CON NUMBER(7,0), RRSEQS NUMBER(6,0),
    RRASAI NUMBER(5,0), RRMSAI NUMBER(3,0), RRDSAI NUMBER(3,0), RRSEQE NUMBER(6,0),
    RRMOVE NUMBER(8,0), PROCESSED_DTTM TIMESTAMP_NTZ(9)
) COMMENT = 'Extract RECREL: ~960K rows | 14 cols';

COPY INTO DB2_RECREL_POC
FROM @INPUT_DATA/RECREL/
FILE_FORMAT = CSV_LATIN1
ON_ERROR = 'CONTINUE';

-- ─────────────────────────────────────────────────────────────────────────────
-- VERIFICATION: Row counts
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 'DB2_ACTA00_POC' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DB2_ACTA00_POC UNION ALL
SELECT 'DB2_ACTA03_POC', COUNT(*) FROM DB2_ACTA03_POC UNION ALL
SELECT 'DB2_ACTA0P_POC', COUNT(*) FROM DB2_ACTA0P_POC UNION ALL
SELECT 'DB2_APOL00_POC', COUNT(*) FROM DB2_APOL00_POC UNION ALL
SELECT 'DB2_APOL03_POC', COUNT(*) FROM DB2_APOL03_POC UNION ALL
SELECT 'DB2_APOL0PH_POC', COUNT(*) FROM DB2_APOL0PH_POC UNION ALL
SELECT 'DB2_APOL0P_POC', COUNT(*) FROM DB2_APOL0P_POC UNION ALL
SELECT 'DB2_APOLPA_POC', COUNT(*) FROM DB2_APOLPA_POC UNION ALL
SELECT 'DB2_ENTREL_POC', COUNT(*) FROM DB2_ENTREL_POC UNION ALL
SELECT 'DB2_ENTVIN_POC', COUNT(*) FROM DB2_ENTVIN_POC UNION ALL
SELECT 'DB2_EVENTO_POC', COUNT(*) FROM DB2_EVENTO_POC UNION ALL
SELECT 'DB2_MOPEC1_POC', COUNT(*) FROM DB2_MOPEC1_POC UNION ALL
SELECT 'DB2_MOVIML_POC', COUNT(*) FROM DB2_MOVIML_POC UNION ALL
SELECT 'DB2_RECI0X_POC', COUNT(*) FROM DB2_RECI0X_POC UNION ALL
SELECT 'DB2_RECIBO_POC', COUNT(*) FROM DB2_RECIBO_POC UNION ALL
SELECT 'DB2_RECPRO_POC', COUNT(*) FROM DB2_RECPRO_POC UNION ALL
SELECT 'DB2_RECREL_POC', COUNT(*) FROM DB2_RECREL_POC
ORDER BY TABLE_NAME;
